## Importing the libraries

In [454]:
import pandas as pd
import numpy as np

## Importing the dataset

In [455]:
dataset = pd.read_csv('credit-approval.csv')
print(dataset.head())

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 class
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202.0    0     +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43.0  560     +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  280.0  824     +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100.0    3     +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120.0    0     +


## Independent Variable

In [456]:
X = dataset.iloc[:, :-1].values

## Dependent Variable

In [457]:
Y = dataset.iloc[:,-1].values

## Checking Missing Data

In [458]:
dataset.isnull().sum()

A1       12
A2       12
A3        0
A4        6
A5        6
A6        9
A7        9
A8        0
A9        0
A10       0
A11       0
A12       0
A13       0
A14      13
A15       0
class     0
dtype: int64

## Handling Missing Data

In [459]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

# imputer.fit(X[:, 0:1])
X[:,0:1] = imputer.fit_transform(X[:, 0:1]) ## always remember that SimpleImputer expects always 2D array

In [460]:
print(X[:, 1:2].dtype)

object


In [461]:
imputer_1 = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer_1.fit(X[:, 1:2])
X[:,1:2] = imputer_1.transform(X[:, 1:2])

In [462]:
imputer_1.fit(X[:, 13:14])
X[:, 13:14] = imputer_1.transform(X[:,13:14])

## Encoding Categorical Data

### Encoding independent variable

In [463]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,3,4,5,6,8,9,11,12])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [464]:
print(ct.get_feature_names_out())

['encoder__x0_a' 'encoder__x0_b' 'encoder__x3_l' 'encoder__x3_u'
 'encoder__x3_y' 'encoder__x3_nan' 'encoder__x4_g' 'encoder__x4_gg'
 'encoder__x4_p' 'encoder__x4_nan' 'encoder__x5_aa' 'encoder__x5_c'
 'encoder__x5_cc' 'encoder__x5_d' 'encoder__x5_e' 'encoder__x5_ff'
 'encoder__x5_i' 'encoder__x5_j' 'encoder__x5_k' 'encoder__x5_m'
 'encoder__x5_q' 'encoder__x5_r' 'encoder__x5_w' 'encoder__x5_x'
 'encoder__x5_nan' 'encoder__x6_bb' 'encoder__x6_dd' 'encoder__x6_ff'
 'encoder__x6_h' 'encoder__x6_j' 'encoder__x6_n' 'encoder__x6_o'
 'encoder__x6_v' 'encoder__x6_z' 'encoder__x6_nan' 'encoder__x8_f'
 'encoder__x8_t' 'encoder__x9_f' 'encoder__x9_t' 'encoder__x11_f'
 'encoder__x11_t' 'encoder__x12_g' 'encoder__x12_p' 'encoder__x12_s'
 'remainder__x1' 'remainder__x2' 'remainder__x7' 'remainder__x10'
 'remainder__x13' 'remainder__x14']


### Encoding Dependent Variable

In [465]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = np.array(le.fit_transform(Y))

In [466]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 

## Splitting the dataset into the Training set and Test set

In [467]:
from sklearn.model_selection import train_test_split

X_train, X_test , Y_train , Y_test = train_test_split(X,Y, test_size=0.2, random_state=1)

In [468]:
print(X_train)
print("-------")
print(X_test)
print("-------")
print(Y_train)
print("-------")
print(Y_test)



[[1.0 0.0 0.0 ... 7 0.0 3065]
 [0.0 1.0 0.0 ... 0 0.0 0]
 [0.0 1.0 0.0 ... 0 440.0 4500]
 ...
 [1.0 0.0 0.0 ... 0 980.0 0]
 [1.0 0.0 0.0 ... 5 220.0 2503]
 [1.0 0.0 0.0 ... 2 300.0 551]]
-------
[[1.0 0.0 0.0 ... 0 180.0 0]
 [0.0 1.0 0.0 ... 1 160.0 234]
 [0.0 1.0 0.0 ... 0 176.0 537]
 ...
 [1.0 0.0 0.0 ... 0 132.0 0]
 [0.0 1.0 0.0 ... 0 0.0 12]
 [0.0 1.0 0.0 ... 11 0.0 284]]
-------
[0 1 1 0 1 1 1 1 0 0 1 0 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1
 0 1 0 1 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0
 1 0 1 0 1 1 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 1 1 0
 1 1 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1 1 0 1 1 1
 0 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 1 0 1 0
 0 1 0 0 0 1 1 0 0 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1
 0 0 1 0 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 1 1
 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 1 0 0
 1 1 0 1 1 1 

## Feature Scaling

In [469]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train[: ,[1, 2, 7, 10, 13, 14]] = sc.fit_transform(X_train[: ,[1, 2, 7, 10, 13, 14]]) 
X_test[: ,[1, 2, 7, 10, 13, 14]] = sc.fit_transform(X_test[: ,[1, 2, 7, 10, 13, 14]])

## train model (just for verification)

In [470]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [471]:
model = RandomForestClassifier()
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)

In [472]:
accuracy = accuracy_score(Y_test, y_pred)
print(accuracy)

0.8695652173913043
