## Importing the libraries

In [1]:
import pandas as pd
import numpy as np

## Importing the dataset

In [2]:
dataset = pd.read_csv('train.csv')
print(dataset.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [3]:
# X = dataset.drop('Survived', axis=1).values
X = dataset[['Pclass', 'Sex', 'Age', 'SibSp',
             'Parch', 'Fare', 'Embarked']].values
y = dataset['Survived'].values

In [4]:
print(X)

[[3 'male' 22.0 ... 0 7.25 'S']
 [1 'female' 38.0 ... 0 71.2833 'C']
 [3 'female' 26.0 ... 0 7.925 'S']
 ...
 [3 'female' nan ... 2 23.45 'S']
 [1 'male' 26.0 ... 0 30.0 'C']
 [3 'male' 32.0 ... 0 7.75 'Q']]


In [5]:
print(y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

## Check missing data

In [6]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## Taking care of Missing data

In [7]:
print(X[:,2])  ## checking missing values for AGE 

[22.0 38.0 26.0 35.0 35.0 nan 54.0 2.0 27.0 14.0 4.0 58.0 20.0 39.0 14.0
 55.0 2.0 nan 31.0 nan 35.0 34.0 15.0 28.0 8.0 38.0 nan 19.0 nan nan 40.0
 nan nan 66.0 28.0 42.0 nan 21.0 18.0 14.0 40.0 27.0 nan 3.0 19.0 nan nan
 nan nan 18.0 7.0 21.0 49.0 29.0 65.0 nan 21.0 28.5 5.0 11.0 22.0 38.0
 45.0 4.0 nan nan 29.0 19.0 17.0 26.0 32.0 16.0 21.0 26.0 32.0 25.0 nan
 nan 0.83 30.0 22.0 29.0 nan 28.0 17.0 33.0 16.0 nan 23.0 24.0 29.0 20.0
 46.0 26.0 59.0 nan 71.0 23.0 34.0 34.0 28.0 nan 21.0 33.0 37.0 28.0 21.0
 nan 38.0 nan 47.0 14.5 22.0 20.0 17.0 21.0 70.5 29.0 24.0 2.0 21.0 nan
 32.5 32.5 54.0 12.0 nan 24.0 nan 45.0 33.0 20.0 47.0 29.0 25.0 23.0 19.0
 37.0 16.0 24.0 nan 22.0 24.0 19.0 18.0 19.0 27.0 9.0 36.5 42.0 51.0 22.0
 55.5 40.5 nan 51.0 16.0 30.0 nan nan 44.0 40.0 26.0 17.0 1.0 9.0 nan 45.0
 nan 28.0 61.0 4.0 1.0 21.0 56.0 18.0 nan 50.0 30.0 36.0 nan nan 9.0 1.0
 4.0 nan nan 45.0 40.0 36.0 32.0 19.0 19.0 3.0 44.0 58.0 nan 42.0 nan 24.0
 28.0 nan 34.0 45.5 18.0 2.0 32.0 26.0 16.0 40

### Age: Age is numeric data, so we apply mean strategy

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer.fit(X[:, 2:3]) # indexes acc to X
X[:,2:3] = imputer.transform(X[:,2:3])

In [9]:
print(X[:,2]) ## Mising values of Age is replaced by mean of all ages

[22.0 38.0 26.0 35.0 35.0 29.69911764705882 54.0 2.0 27.0 14.0 4.0 58.0
 20.0 39.0 14.0 55.0 2.0 29.69911764705882 31.0 29.69911764705882 35.0
 34.0 15.0 28.0 8.0 38.0 29.69911764705882 19.0 29.69911764705882
 29.69911764705882 40.0 29.69911764705882 29.69911764705882 66.0 28.0 42.0
 29.69911764705882 21.0 18.0 14.0 40.0 27.0 29.69911764705882 3.0 19.0
 29.69911764705882 29.69911764705882 29.69911764705882 29.69911764705882
 18.0 7.0 21.0 49.0 29.0 65.0 29.69911764705882 21.0 28.5 5.0 11.0 22.0
 38.0 45.0 4.0 29.69911764705882 29.69911764705882 29.0 19.0 17.0 26.0
 32.0 16.0 21.0 26.0 32.0 25.0 29.69911764705882 29.69911764705882 0.83
 30.0 22.0 29.0 29.69911764705882 28.0 17.0 33.0 16.0 29.69911764705882
 23.0 24.0 29.0 20.0 46.0 26.0 59.0 29.69911764705882 71.0 23.0 34.0 34.0
 28.0 29.69911764705882 21.0 33.0 37.0 28.0 21.0 29.69911764705882 38.0
 29.69911764705882 47.0 14.5 22.0 20.0 17.0 21.0 70.5 29.0 24.0 2.0 21.0
 29.69911764705882 32.5 32.5 54.0 12.0 29.69911764705882 24.0
 29.

### Embarked : text/categorical data, so we apply most_frequent startegy

In [10]:
print(X[:,6])   ## checking missing values for Embarked

['S' 'C' 'S' 'S' 'S' 'Q' 'S' 'S' 'S' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'Q' 'S'
 'S' 'C' 'S' 'S' 'Q' 'S' 'S' 'S' 'C' 'S' 'Q' 'S' 'C' 'C' 'Q' 'S' 'C' 'S'
 'C' 'S' 'S' 'C' 'S' 'S' 'C' 'C' 'Q' 'S' 'Q' 'Q' 'C' 'S' 'S' 'S' 'C' 'S'
 'C' 'S' 'S' 'C' 'S' 'S' 'C' nan 'S' 'S' 'C' 'C' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'Q' 'S' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'S' 'S' 'S' 'S' 'S' 'C' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'Q' 'S' 'C' 'S' 'S' 'C' 'S' 'Q' 'S' 'C' 'S' 'S' 'S' 'C' 'S' 'S' 'C'
 'Q' 'S' 'C' 'S' 'C' 'S' 'S' 'S' 'S' 'C' 'S' 'S' 'S' 'C' 'C' 'S' 'S' 'Q'
 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'C' 'Q' 'S' 'S' 'S' 'S' 'S'
 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'Q' 'S' 'S' 'C' 'S' 'S' 'C' 'S' 'S'
 'S' 'C' 'S' 'S' 'S' 'S' 'Q' 'S' 'Q' 'S' 'S' 'S' 'S' 'S' 'C' 'C' 'Q' 'S'
 'Q' 'S' 'S' 'S' 'S' 'C' 'S' 'S' 'S' 'C' 'Q' 'C' 'S' 'S' 'S' 'S' 'Q' 'C'
 'S' 'S' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'S' 'S' 'S' 'S' 'S' 'C' 'Q' 'S' 'S' 'C' 'Q' 'S

In [11]:
imputer_1= SimpleImputer(missing_values=np.nan , strategy='most_frequent')
imputer_1.fit(X[:,6:7]) # indexes acc to X
X[:, 6:7] = imputer_1.transform(X[:,6:7])

In [12]:
print(X[:,6]) ## Mising values of Embarked is replaced by most frequents of Embarked

['S' 'C' 'S' 'S' 'S' 'Q' 'S' 'S' 'S' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'Q' 'S'
 'S' 'C' 'S' 'S' 'Q' 'S' 'S' 'S' 'C' 'S' 'Q' 'S' 'C' 'C' 'Q' 'S' 'C' 'S'
 'C' 'S' 'S' 'C' 'S' 'S' 'C' 'C' 'Q' 'S' 'Q' 'Q' 'C' 'S' 'S' 'S' 'C' 'S'
 'C' 'S' 'S' 'C' 'S' 'S' 'C' 'S' 'S' 'S' 'C' 'C' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'Q' 'S' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'S' 'S' 'S' 'S' 'S' 'C' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'Q' 'S' 'C' 'S' 'S' 'C' 'S' 'Q' 'S' 'C' 'S' 'S' 'S' 'C' 'S' 'S' 'C'
 'Q' 'S' 'C' 'S' 'C' 'S' 'S' 'S' 'S' 'C' 'S' 'S' 'S' 'C' 'C' 'S' 'S' 'Q'
 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'C' 'Q' 'S' 'S' 'S' 'S' 'S'
 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'Q' 'S' 'S' 'C' 'S' 'S' 'C' 'S' 'S'
 'S' 'C' 'S' 'S' 'S' 'S' 'Q' 'S' 'Q' 'S' 'S' 'S' 'S' 'S' 'C' 'C' 'Q' 'S'
 'Q' 'S' 'S' 'S' 'S' 'C' 'S' 'S' 'S' 'C' 'Q' 'C' 'S' 'S' 'S' 'S' 'Q' 'C'
 'S' 'S' 'C' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S' 'S'
 'S' 'S' 'S' 'S' 'S' 'S' 'C' 'Q' 'S' 'S' 'C' 'Q' 'S

## Encoding categorical data

### Encoding the Independent Variable

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,6])], remainder='passthrough')
X= np.array(ct.fit_transform(X))

In [14]:
print(ct.get_feature_names_out()) ##encoded variables will come first, and then remaining.... 

['encoder__x1_female' 'encoder__x1_male' 'encoder__x6_C' 'encoder__x6_Q'
 'encoder__x6_S' 'remainder__x0' 'remainder__x2' 'remainder__x3'
 'remainder__x4' 'remainder__x5']


### Encoding the Dependent Variable

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = np.array(le.fit_transform(y))

In [16]:
print(y) ## label enoded 

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

## Splitting the dataset into the Training set and Test set

In [17]:
print(X[0])

[0.0 1.0 0.0 0.0 1.0 3 22.0 1 0 7.25]


In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)

In [19]:
print(pd.DataFrame(X_train))

       0    1    2    3    4  5          6  7  8        9
0    0.0  1.0  0.0  1.0  0.0  3  29.699118  2  0    23.25
1    1.0  0.0  1.0  0.0  0.0  1       30.0  0  0  56.9292
2    1.0  0.0  0.0  0.0  1.0  2       34.0  0  0     10.5
3    0.0  1.0  0.0  0.0  1.0  2       21.0  2  0     73.5
4    0.0  1.0  0.0  0.0  1.0  2       62.0  0  0     10.5
..   ...  ...  ...  ...  ... ..        ... .. ..      ...
707  0.0  1.0  0.0  0.0  1.0  3       19.0  0  0     7.65
708  1.0  0.0  0.0  1.0  0.0  3       30.5  0  0     7.75
709  0.0  1.0  0.0  0.0  1.0  2       21.0  0  0     73.5
710  1.0  0.0  0.0  0.0  1.0  3  29.699118  0  0     7.55
711  0.0  1.0  0.0  0.0  1.0  3       21.0  0  0     8.05

[712 rows x 10 columns]


In [20]:
print(X_test)

[[1.0 0.0 0.0 ... 0 0 25.9292]
 [0.0 1.0 0.0 ... 0 0 7.8958]
 [1.0 0.0 0.0 ... 0 0 10.5]
 ...
 [0.0 1.0 0.0 ... 0 0 7.7333]
 [0.0 1.0 0.0 ... 0 0 7.7333]
 [1.0 0.0 1.0 ... 2 1 19.2583]]


In [21]:
print(y_train)

[1 1 1 0 1 1 0 0 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 0 1 0
 0 1 1 0 1 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 0
 1 1 0 0 1 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0
 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 1 1 1
 1 1 1 1 0 0 0 0 0 0 1 0 1 1 0 1 0 1 1 1 0 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1
 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 1 1 1 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0
 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0
 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 1 1 1 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0
 1 1 1 0 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 1 1 0 0 1 1
 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0
 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0 1 0 0 1
 0 1 1 1 0 1 1 1 0 1 0 1 

In [22]:
print(y_test)

[1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0 1 0 0 0 1 1
 0 1 0 1 1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0
 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1
 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 1 0 0 1 0 1 0 0 0
 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0 1 0 0 0 1]


## Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,5:] = sc.fit_transform(X_train[:,5:])
X_test[:,5:] = sc.transform(X_test[:,5:])

In [24]:
print(pd.DataFrame(X_train))

       0    1    2    3    4         5         6         7         8         9
0    0.0  1.0  0.0  1.0  0.0  0.836593 -0.028105  1.491053 -0.478173 -0.188014
1    1.0  0.0  1.0  0.0  0.0 -1.555593 -0.005412   -0.4896 -0.478173   0.53969
2    1.0  0.0  0.0  0.0  1.0   -0.3595  0.296271   -0.4896 -0.478173 -0.463503
3    0.0  1.0  0.0  0.0  1.0   -0.3595   -0.6842  1.491053 -0.478173  0.897735
4    0.0  1.0  0.0  0.0  1.0   -0.3595  2.408055   -0.4896 -0.478173 -0.463503
..   ...  ...  ...  ...  ...       ...       ...       ...       ...       ...
707  0.0  1.0  0.0  0.0  1.0  0.836593 -0.835042   -0.4896 -0.478173 -0.525083
708  1.0  0.0  0.0  1.0  0.0  0.836593  0.032298   -0.4896 -0.478173 -0.522922
709  0.0  1.0  0.0  0.0  1.0   -0.3595   -0.6842   -0.4896 -0.478173  0.897735
710  1.0  0.0  0.0  0.0  1.0  0.836593 -0.028105   -0.4896 -0.478173 -0.527243
711  0.0  1.0  0.0  0.0  1.0  0.836593   -0.6842   -0.4896 -0.478173  -0.51644

[712 rows x 10 columns]


## train model (just for verification)

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [26]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [27]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.776536312849162
